#! /bin/bash

xhost +local:

docker run \
    -e DISPLAY=$DISPLAY \
    -e USER=$(whoami) \
    -v /home:/home \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v $HOME/.Xauthority:/root/.Xauthority \
    --rm -it auth-app