#! /bin/bash

sudo cp -r . /opt/auth

bash /opt/auth/build/create-conf

sudo apt-get update && \
    xargs apt-get install -y < ./build/packages/cli

sudo python -m venv /opt/auth/venv

sudo /opt/auth/venv/bin/pip install --no-cache-dir -r ./build/packages/python