#! /bin/bash

[ -f .env ] && source .env

case $1 in
    build)
        IMG=$2
        NAME=$3

        docker build \
            --build-arg USER=$(whoami) \
            --build-arg UID=$(id -u) \
            --build-arg GID=$(id -g) \
            --build-arg IMG=app.$IMG \
            -t app.$NAME .
    ;;
    build-dev)
        IMG=$2
        NAME=$3

        docker build \
            --build-arg USER=$(whoami) \
            --build-arg IMG=app.$IMG \
            -t app.$NAME /$ZSH
    ;;
    run-dev)
        NAME=$2

        docker run \
            --name run.$NAME \
            -e DISPLAY=$DISPLAY \
            -e USER=$(whoami) \
            -e DEV=true \
            -v /tmp/.X11-unix:/tmp/.X11-unix \
            -v $HOME/.Xauthority:/root/.Xauthority \
            -v $(pwd):/usr/src/app \
            --rm -dit app.$NAME
    ;;
    run)
        NAME=$2

        docker run \
            --name run.$NAME \
            -e DISPLAY=$DISPLAY \
            -e USER=$(whoami) \
            -v /home:/home \
            -v /tmp/.X11-unix:/tmp/.X11-unix \
            -v $HOME/.Xauthority:/root/.Xauthority \
            --rm -it app.$NAME
    ;;
    commit)
        NAME=$2

        docker commit -p run.$NAME app.$NAME
    ;;
    shell)
        NAME=$2

        docker exec -it run.$NAME /bin/zsh
    ;;
    shell-root)
        NAME=$2

        docker exec -u 0 -it run.$NAME /bin/bash
    ;;

esac